### ISSUE TITLE
getRelated() calls on eagerly loaded models doesn't work

### ISSUE THREAD

**Issue by Toflar** [terminal42/contao-DC_Multilingual#29]
Because the JOIN query is not built multilingual (it works in terms of the data set gets loaded but not the translated one)

**Comment by aschempp** [comment]
I think the only solution will be to disable eager loading of all multilingual records.

**Comment by qzminski** [comment]
I think so, too.

**Comment by aschempp** [comment]
How should we do that? We don't really have any influence on how Contao loads the models?

**Comment by qzminski** [comment]
We can adjust the DCA if DC_Multilingual is set as a driver.

**Comment by aschempp** [comment]
well that wouldn't solve the problem of eagerly-loading a multilingual model from another DCA. But the developer can solve that, so not sure if we actually need to do anything here…?

**Comment by Toflar** [comment]
Can we override the `getRelated()` method in the `MultilingualModel` and check if `eager` is set and in that case throw an exception so at least the developers know why it's not working and what they should do?
