### ISSUE TITLE
copy funktion in DC_Multilingual.php

### ISSUE THREAD

**Issue by css-umsetzung** [terminal42/contao-DC_Multilingual#30]
Die Copy funktionen berücksichtigen  nicht die Felder die auf donotcopy gesetzt wurden.
leider gibt es auch keine möglichkeit das nachträglich über einen hook zu regeln.

**Comment by aschempp** [comment]
Meinst du das generell oder nur bei den Übersetzungen/Sprachversionen?

**Comment by css-umsetzung** [comment]
nur bei den Spachversionen, die originale Version wird so kopiert dass die donotcopy Felder leer sind.

**Comment by aschempp** [comment]
Should be fixed in ff0c0542f5d0aabb749bc830b23eaa3d98d97966

**Comment by css-umsetzung** [comment]
leider wird mit dem fix nicht mehr die language Spalte befüllt
langPid bekommt die richtige ID alber language  bleibt leer, dadurch fehlt die zuordnung und es wird beim umschalten ein neuer Datensatz angelegt.

**Comment by aschempp** [comment]
da hast du Recht! Sollte mit 315cefa45904cafa699b3b9ca4d4b828e32f1300 behoben sein.
