### ISSUE TITLE
Fallback nutzen wenn ein Feld übersetzbar aber leer ist

### ISSUE THREAD

**Issue by joke1** [terminal42/contao-DC_Multilingual#31]
Hi,

spricht etwas dagegen, den QueryBuilder so zu ändern, dass der Fallback auch bei einem übersetzbaren aber leeren Feld genutzt wird? In meinem Modul habe ich die Datei entsprechend überschrieben. Vielleicht wäre aber ein DCA-Setting ganz nützlich?

MultilingualQueryBuilder.php Zeile 142:

```
return "IFNULL(" . $strSecondTable . "." . $varFields . ", " . $strFirstTable . "." . $varFields . ") AS " . (strlen($strPrefix) ? $strPrefix : "") . $varFields;
```

```
return "CASE WHEN " . $strSecondTable . "." . $varFields . " IS NULL OR " . $strSecondTable . "." . $varFields . " = '' THEN " . $strFirstTable . "." . $varFields . " ELSE " . $strSecondTable . "." . $varFields . " END AS " . (strlen($strPrefix) ? $strPrefix : "") . $varFields;
```

**Comment by Toflar** [comment]
Es spricht insofern was dagegen, als dass `''` nicht das einzige ist was für "leer" steht. Wenn z.B. eine ID drin stehen sollte, dann wäre es ja `0`, abhängig vom Feldtypen halt. 

> Vielleicht wäre aber ein DCA-Setting ganz nützlich?

Ja, müsste aber meinen beschriebenen Fall dann auch abdecken. Pull Requests welcome :)

**Comment by aschempp** [comment]
Dafür gibt's in Contao doch eine Methode welche den Default-Wert "herausfindet" ?

**Comment by joke1** [comment]
Danke für die Hinweise!
Da ich eigentlich nur FE'ler bin, mag ich den ggf. entstandenen Stuss nicht als Pull Request einreichen ;) Vielleicht kann damit ja aber jemand was anfangen, der da mehr Ahnung von hat.

Mein generateFieldsSubquery sieht nun so aus:

```
    public static function generateFieldsSubquery($varFields, $strFirstTable, $strSecondTable, $table, $strPrefix='')
    {
        if (is_array($varFields))
        {
            $arrReturn = array();

            foreach ($varFields as $field)
            {
                $arrReturn[] = static::generateFieldsSubquery($field, $strFirstTable, $strSecondTable, $table, $strPrefix);
            }

            return $arrReturn;
        }

        if($GLOBALS['TL_DCA'][$table]['config']['useFieldFallback']) {
            $emptyValueField = json_encode(\Widget::getEmptyValueByFieldType($GLOBALS['TL_DCA'][$table]['fields'][$varFields]['sql']));
            return "CASE WHEN " . $strSecondTable . "." . $varFields . " IS NULL OR " . $strSecondTable . "." . $varFields . " = " . $emptyValueField . " THEN " . $strFirstTable . "." . $varFields . " ELSE " . $strSecondTable . "." . $varFields . " END AS " . (strlen($strPrefix) ? $strPrefix : "") . $varFields;
        }

        return "IFNULL(" . $strSecondTable . "." . $varFields . ", " . $strFirstTable . "." . $varFields . ") AS " . (strlen($strPrefix) ? $strPrefix : "") . $varFields;
    }
```

Den Aufruf der Funktion innerhalb von find() hab ich entsprechend angepasst (Zeile 51):
```
$strQuery = "SELECT dcm1.*" . (!empty($arrLanguageFields) ? (", " . implode(", ", static::generateFieldsSubquery($arrLanguageFields, 'dcm1', 'dcm2', $arrOptions['table']))) : "") . " FROM " . $arrOptions['table'] . " AS dcm1";
```

Über folgendes DCA Setting wird das ausgelöst:
```
$GLOBALS['TL_DCA']['_TABLE_']['config']['useFieldFallback'] = true;
```

**Comment by Toflar** [comment]
Jo, das ist schon ganz gut für einen FE'ler find ich ;) Ich denke aber, dass man das pro Feld aktivieren können sollte und nicht generell für die Tabelle. Ich markiere es einfach als Feature für eine zukünftige Version. Wenn es mal jemand braucht (oder wir selbst) entsteht daraus dann hoffentlich ein PR :) Danke für den Input :+1:

**Comment by aschempp** [comment]
Ich denke das hat sich in der Zwischenzeit erledigt. Sonst gerne einen Pull Request dazu.
