### ISSUE TITLE
PHP7 compatibilty issue

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-DC_Multilingual#33]
Guess it should be changed to ```\StringUtil```?

https://github.com/terminal42/contao-DC_Multilingual/blob/master/drivers/DC_Multilingual.php#L1091

**Comment by Toflar** [comment]
Yes but we can release it as a bugfix if we do the `version_compare` stuff. And we should merge https://github.com/terminal42/contao-DC_Multilingual/pull/32/files as well. Can you take care?

**Comment by qzminski** [comment]
Fixed in bbe69d7.
