### ISSUE TITLE
Aufruf eines Models sprachenabhängig

### ISSUE THREAD

**Issue by css-umsetzung** [terminal42/contao-DC_Multilingual#34]
Wenn ich in einem Durchgang,
das gleiche Objekt eines Model in zwei verschiedenen Sprachen aufrufe, habe ich das Problem, dass ich immer nur die Sprachversion des zuerst aufgerufenen Objekts sehe, dies ist ja vermutlich das Problem der Models überhaupt weil ich nicht sagen kann, das ich etwas nicht im cache haben möchte.

Da ich aber in dem Model auch nicht sehe, welche Sprache ich letztendlich ausgeworfen bekommen habe, kann ich nicht einmal prüfen, ob ich das unregister verwenden und das Object neu holen soll.

wenn dort etwas wie dieses hier im query vorhanden wäre, hätte man zumindest eine Kontrollfunktion
für "de" würde natürlich die default Sprache oder ein empty string stehen. 

   	IFNULL(
		dcm2.language,"de"
	) AS used_lang, 

Ich habe dieses Problem aktuell weil ich in einem Cron, ein Objekt mehrfach in der Hand habe, bisher bin ich davon ausgegangen, dass die Übergabe des Parameters "language" ausreicht das das Multilangual mir immer den richtigen Datensatz übergibt.

**Comment by Toflar** [comment]
Also Kurzfassung: Das Model ist nur 1x in der Registry?

**Comment by css-umsetzung** [comment]
ja

wenn ich diesen Aufruf mache
\owpGames\OwpEventModel::findByPk(60,array('language'=> "de"));
habe ich das Model in der Sprache "de" mit allen deutschen Daten

mache ich danach 
\owpGames\OwpEventModel::findByPk(60,array('language'=> "en"));

dann bekomme ich wieder die Deutsche Version vom ersten Aufruf.
Da Ihr nicht die aktuelle Sprache liefert, die Ihr wirklich ausgelesen habt, kann ich auch nicht kontrollieren, ob der Datensatz wirklich der ist den ich möchte, denn dann hätte ich zumindest die Möglichkeit das Model über ein unregister() zu killen und neu auszulesen, was auch Pfusch ist mir aber helfen würde.

**Comment by Toflar** [comment]
Das liegt an der Model Registry, nicht an Multilingual Model selbst. Du müsstest dafür sorgen, dass das Model beim Registrieren in der Registry die Sprache berücksichtigt. Denn die ID wird ja nicht übersetzt und somit denkt die Registry du willst 2x denselben Datensatz. Wäre natürlich optimal, wenn das Multilingual Model das automatisch berücksichtigen könnte. Müsste man sich mal ansehen ob das überhaupt so einfach geht.

**Comment by css-umsetzung** [comment]
Ich weiss das es nicht an euch liegt, daher war meine idee ja das ihr zumindest die ausgelieferte sprache festhaltet, das ginge ja vermutlich auch in der eh vorhandenen spalte language, damit man zumindest eine kontrollmöglichkeit hat. Denn wenn man nicht sicher sein kann das man zurück bekommt was man angefragt hat, macht das ganze Models keinen Sinn.

Eine Datenbank die eine Eindeutige id  hat ist ja dafür da, das man danach fragt.

**Comment by aschempp** [comment]
Das Problem ist in 2.1.4 behoben.
