### ISSUE TITLE
Bug in getLangaugeId() method

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-DC_Multilingual#36]
I am pretty sure there is a bug in the ```Multilingual::getLanguageId()``` method:

https://github.com/terminal42/contao-DC_Multilingual/blob/develop/src/Model/Multilingual.php#L24

That line should call ```getPidColumn()``` instead. Otherwise the method can either return the language string (e.g. ```de```) or the current record ID (e.g. ```123```).

**Comment by aschempp** [comment]
Sounds reasonable

**Comment by Toflar** [comment]
Sounds ok yeah

**Comment by qzminski** [comment]
Fixed in e995e7d.
