### ISSUE TITLE
Problem with getAlias() method using model registry

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-DC_Multilingual#37]
The ```MultilingualModel::getAlias``` method cannot work correctly because it uses the ```findByPk()``` method which uses the model registry. So given that we have fetched the record with ID 123 from the database, the line

https://github.com/terminal42/contao-DC_Multilingual/blob/develop/src/Model/Multilingual.php#L53

will keep returning the very same ID 123 model. That's because it calls the ```findByPk()``` method

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Model.php#L789

which then calls the ```find()``` method which checks the model registry and tries to load from there:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Model.php#L1043-L1058

Thus the ```language``` option passed in cannot even get into the ```buildFindQuery()``` method :-(

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Model.php#L1061

**Comment by aschempp** [comment]
I guess we need to override `findByPk` and check the language option?

**Comment by qzminski** [comment]
I would create an individual method because ```findByPk``` indicates we are searching by ID but in fact the returned model can have a different primary key.

**Comment by aschempp** [comment]
well if the method supports the `language` option shouldn't it work in all cases?

**Comment by qzminski** [comment]
Maybe yes...

**Comment by Toflar** [comment]
Our "pk" should be `id,language` :)

**Comment by aschempp** [comment]
Yeah, but Contao does not support multiple PKs ;-)

**Comment by Toflar** [comment]
No system can have multiple PK's, that's why it's named PK. Anyway. What I meant is we should provide a method to find by ID and language.

**Comment by aschempp** [comment]
I did mean a PK with multiple columns, which is supported by all DBs and also by Doctrine (but not by Contao models).

**Comment by qzminski** [comment]
As discussed on the phone for now the best option to avoid the problems with registry and updating the model data is to prevent model from saving. Fixed in 6b913f0.
