### ISSUE TITLE
Kopieren von Inhalten aus Fallback-Sprache

### ISSUE THREAD

**Issue by cboelter** [terminal42/contao-DC_Multilingual#38]
Hi,

ich habe bei einem Projekt gerade folgende Anforderung:

Bestimmte Daten aus der Fallback-Sprache sollen beim anlegen einer neuen Sprache in diese hineinkopiert werden. So habe ich dann bei bestimmten Feldern, der neuen Sprache, keine leeren Felder sondern den Inhalt der Fallback-Sprache um ggf. Teile davon zu übersetzen.

Beispiel dafür wäre ein TinyMCE-Feld mit viel Inhalt (mit Bildern etc.). Dort müsste der Inhalt dann nicht komplett neu aufgebaut oder manuelle kopiert werden, sondern es müsste lediglich der Text ausgetauscht werden.

Wäre das generell ein sinnvolles Feature für den DC_Multilingual?
Wenn ja, würde ich einen Pull-Request dafür machen.

**Comment by aschempp** [comment]
Ein ähnliches Feature gibt es in Isotope eCommerce, dessen DC_ProductData ziemlich gleich aufgebaut ist (aber aus historischen Gründen nicht darauf basiert). Dort haben wir einfach eine Option "alles Kopieren". Generell finde ich das sinnvoll, entweder einfach alles oder "selektiv"…

**Comment by cboelter** [comment]
Ich habe mir die Funktion in Isotope einmal angesehen. Die tut ja grundsätzlich schon in etwa das was ich mir für den Dc_Multilingual auch wünsche. Ich würde mir das ganze wie folgt vorstellen:

**Wann wird kopiert?**
Konfiguration im DCA, dort kann gewählt ob automatisch oder manuell kopiert werden soll. Wenn die Einstellung leer ist, wird das nicht aktiviert. Wenn manually gewählt ist, wird wie bei Isotope ein Link zur Verfügung gestellt, bei automatically wird direkt beim erzeugen der Sprache der Inhalt kopiert.

`$GLOBALS['TL_DCA']['table']['config']['copyFromFallbackLanguage'] = 'manually';`
`$GLOBALS['TL_DCA']['table']['config']['copyFromFallbackLanguage'] = 'automatically';`

**Welche Felder werden kopiert:**
Bei der Auswahl welche Felder kopiert werden, stelle ich mir auch zwei Varianten vor. 
1. Alle Felder werden kopiert, wird per im Konfiguration DCA aktiviert
`$GLOBALS['TL_DCA']['table']['config']['copyAllFields'] = true;`
2. Nur ausgewählte Felder werden kopiert, die Steuerung erfolgt über ein eval field
`$GLOBALS['TL_DCA']['table']['fields']['field']['eval']['copyFromFallback'] = true;`

Beim kopieren der Felder muss dann noch geprüft werden, ob diese Felder in der Zielspache überhaupt zur Verfügung stehen.

Ideen dazu?

**Comment by aschempp** [comment]
Grundsätzlich würde ich das auch so lösen. Die Flags scheinen mir etwas kompliziert, beispielsweise braucht es kein `copyAllFields` weil das definiert sich einfach darüber dass nirgends ein `copyFromFallback` gesetzt wäre, oder?

**Comment by aschempp** [comment]
Ich denke das hat sich in der Zwischenzeit erledigt. Sonst gerne einen Pull Request dazu.
