### ISSUE TITLE
Fehler beim Anlegen eines Attributes unter Contao 4.3.2

### ISSUE THREAD

**Issue by Benjaminscherf** [terminal42/contao-DC_Multilingual#39]
Hallo,

vorab - ich weiß nicht genau ob es hier der richtige Ort ist oder eher bei Isotope. 

Ich versuche Isotope 2.4.0 unter Contao 4.3.2 zum laufen zu bringen. Soweit ich es sagen kann funktioniert erst einmal alles, ausser das Anlegen eines Attributes. Sobald man zum Bereich "Optionen-Quelle" kommt und eine Auswahl trifft, erscheint folgender Fehler:

Strict Standards: Declaration of DC_Multilingual::generateTree() should be compatible with Contao\DC_Table::generateTree($table, $id, $arrPrevNext, $blnHasSorting, $intMargin = 0, $arrClipboard = NULL, $blnCircularReference = false, $protectedPage = false, $blnNoRecursion = false, $arrFound = Array) in /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php on line 1463

Das betrifft nur die Auswahl "Options-Manager" und "Produkt".

Im Frontend erscheint folgende Meldung:

Strict Standards: Declaration of DC_Multilingual::generateTree() should be compatible with Contao\DC_Table::generateTree($table, $id, $arrPrevNext, $blnHasSorting, $intMargin = 0, $arrClipboard = NULL, $blnCircularReference = false, $protectedPage = false, $blnNoRecursion = false, $arrFound = Array) in /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php:24) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 657

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php:24) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php:24) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149

Könnt Ihr hierzu was sagen bzw. einen Tip geben. 
LG

**Comment by jedoStyle** [comment]
bei mir hatte ich den Fehler auch in Isotope,

ich musste nur die Zeile mit der Funktion "generateTree"  wie folgt anpassen (DC_Multilingual.php)
`protected function generateTree($table, $id, $arrPrevNext, $blnHasSorting, $intMargin=0, $arrClipboard=null, $blnCircularReference=false, $protectedPage=false, $blnNoRecursion=false, $arrFound=array())`

**Comment by aschempp** [comment]
Duplicate of https://github.com/isotope/core/issues/1753

**Comment by aschempp** [comment]
Fixed in Version 2.1.7 (54630b66fca7bb778df054d3ad4028eff3ff52b7)
