### ISSUE TITLE
Check if field in database exists before adding to querybuilder

### ISSUE THREAD

**Issue by fatcrobat** [terminal42/contao-DC_Multilingual#46]
We currently try to make DC_Multilingual work with [contao-rocksolid-custom-elements](https://github.com/madeyourday/contao-rocksolid-custom-elements) and recognized that dummy elements added to dca by `contao-rocksolid-custom-elements` do not really have an database mapping.

The following error messages will occur, because all data is stored in `rsce_data` and fields like `rsce_field_boxes__0__headline` need no database mapping.

```
IFNULL(t2.rsce_field_boxes__0__headline, t1.rsce_field_boxes__0__headline) AS rsce_field_boxes__0__headline
```

The method `Terminal42\DcMultilingualBundle\Model\Multilingual::getMultilingualQueryBuilder()` should only add existing database fields to the `terminal42.dc_multilingual.querybuilder_factory`. 

Two adjustments should be made to fix this behavior:

```
/**
     * Get the regular fields.
     *
     * @return array
     */
    protected static function getRegularFields()
    {
        $sqlFields = Database::getInstance()->getFieldNames(static::getTable());

        $extractor = \DcaExtractor::getInstance(static::getTable());

        return array_intersect($sqlFields, array_keys($extractor->getFields()));
    }
```

```
/**
     * Get the fields that are translatable.
     *
     * @return array
     */
    protected static function getTranslatableFields()
    {
        $sqlFields = Database::getInstance()->getFieldNames(static::getTable());

        static::ensureDataContainerIsLoaded();

        $fields = [];

        foreach ($GLOBALS['TL_DCA'][static::getTable()]['fields'] as $field => $data) {
            if (!isset($data['eval']['translatableFor']) || !in_array($field, $sqlFields)) {
                continue;
            }

            $fields[] = $field;
        }

        return $fields;
    }
```

**Comment by Toflar** [comment]
Can you create a PR please?

**Comment by fatcrobat** [comment]
Here you go: https://github.com/terminal42/contao-DC_Multilingual/pull/50
