### ISSUE TITLE
Contao 4.x: Fix delete language, add novalidate to <form> element in Driver::edit()

### ISSUE THREAD

**Issue by fatcrobat** [terminal42/contao-DC_Multilingual#49]
Delete of languages currently only works without mandatory fields due to html5 validation. Contao core DC_Table has `novalidate` flag set in `form` tag by default.

**Comment by Toflar** [comment]
Please submit a PR to fix the issue.

**Comment by fatcrobat** [comment]
Here you go: https://github.com/terminal42/contao-DC_Multilingual/pull/50
