### ISSUE TITLE
why "preventSaving"?

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-DC_Multilingual#51]
If you try to do the following:
```php
$model = new FooModel();
$model->title = 'Foo';
$model->save();
```
and `FooModel` extends from `Terminal42\DcMultilingualBundle\Model\Multilingual`, an error will occur saying
```
The model instance has been detached and cannot be saved
```
where as with other models there won't be such an error. The reason for this is the constructor of `Terminal42\DcMultilingualBundle\Model\Multilingual` which happens to have this line:

https://github.com/terminal42/contao-DC_Multilingual/blob/56c0fbd77277dd840fc043645d37c6e9c6e799df/src/Model/Multilingual.php#L28

I am assuming there is a specific reason for that - but what exact reason is it? 😄 

Currently for Multilingual models, you have to do the following workaround in order to be able to create and save them:
```php
$model = clone (new FooModel());
$model->title = 'Foo';
$model->save();
```
Which seems a bit odd.

**Comment by aschempp** [comment]
Hier steht die Begründung: https://github.com/terminal42/contao-DC_Multilingual/commit/afd78f308a15e1c8c0f8c9c453ec7a44232d136e#commitcomment-16817605

Ein Multilingual-Model ist eine Zusammenführung von zwei Datensätzen (Parent und Sprachelement). Darf man das nie speichern können.

Wir könnten das höchstens nur verbieten wenn es zusammengeführt wurde. Also z.B. nur wenn es von unserem QueryBuilder kommt 🤔

**Comment by fritzmg** [comment]
I see, makes sense. However, yeah, it would be good if `preventSaving` wasn't applied by default.

In my case I simply wanted to create a new `NewsCategoryModel` instance from [codefog/contao-news_categories](https://github.com/codefog/contao-news_categories/). However, this model automatically extends `\Terminal42\DcMultilingualBundle\Model\Multilingual` when present: 

https://github.com/codefog/contao-news_categories/blob/85fe0094da33f4dc22f73346a9dddd43a939ca12/src/Model/NewsCategoryModel.php#L25-L35

Thus I had no choice but to use the `clone` workaround.

**Comment by richardhj** [comment]
> Wir könnten das höchstens nur verbieten wenn es zusammengeführt wurde. Also z.B. nur wenn es von unserem QueryBuilder kommt 🤔

Meine Idee wäre, das `preventSaving()` in `preFind($objStatement)` aufzurufen (anstatt im Constructor), und zwar nur dann, wenn im Statement ein JOIN vorhanden ist.

**Comment by aschempp** [comment]
In `preFind` haben wir aber noch gar kein Model, das ist ja eine Static-Methode?

**Comment by richardhj** [comment]
Wir könnten im `preFind` eine Flag setzen, und darauf im Constructor `preventSaving()` aufrufen.

**Comment by aschempp** [comment]
🤔 hört sich gefährlich an. Wenn die Suche kein Resultat ausgibt würde der Constructor nicht aufgerufen. `postFind` nützt da ja auch nichts. Ginge es vielleicht mit `createModelFromDbResult`?

**Comment by richardhj** [comment]
`createModelFromDbResult` wird halt nicht aufgerufen, wenn eine Collection zurückgegben wird (see  Model:1123)

**Comment by aschempp** [comment]
Klar, dasselbe müsste auch in der `createCollectionFromDbResult` gemacht werden

**Comment by richardhj** [comment]
@fritzmg @aschempp Please review the following change: https://github.com/terminal42/contao-DC_Multilingual/compare/9f702a1c6c1f0a46bf822f6c35c4e682637b1c64...21c30dfb34c7bf117f35860b9d5fe2bf17689275

**Comment by fritzmg** [comment]
Hm. I don't think you need to prevent saving for `createCollection`. The models in `$arrModels` should already have `preventSaving: true`, if they were loaded from the database. And if the models were newly created, they shouldn't be forced to prevent saving.

**Comment by richardhj** [comment]
👍
