### ISSUE TITLE
Make sure to get rid of the `System::setCookie('BE_PAGE_OFFSET', 0, 0);` calls

### ISSUE THREAD

**Issue by Toflar** [terminal42/contao-DC_Multilingual#52]

**Comment by qzminski** [comment]
Why? It seems still quite common in Contao 4.7.

**Comment by Toflar** [comment]
Because they kill the reverse proxy cache in 4.8. The issue is (apart from the fact that it should be session storage and JS only) that the cookie is not restricted to `/contao` so it sets a cookie for the FE as well. They are removed in master and replaced by JS, see https://github.com/contao/contao/pull/467.
So either we just remove it and don't care about 4.4 or we should at least add `/contao` so the cookies are only set for the back end.

**Comment by qzminski** [comment]
Changed in 8dbea5d.
