### ISSUE TITLE
example with tl_user not working?

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-DC_Multilingual#53]
I was trying to make some fields of `tl_user` translatable. I added the configuration, just like it is explained in the README: https://github.com/terminal42/contao-DC_Multilingual#example-usage

However, when switching the `dataContainer` to `Multilingual`, the back end (at least in Contao 4.7.6) does not show any database entries in the user management anymore.

Is there something I am missing?

**Comment by fritzmg** [comment]
Ah, the problem is, that `tl_user` already contains a field  called `language` - which is the user's language and has nothing to do with the translations. DC_Multilingual automatically adds a filter on the configured language field and thus this causes no entries to be shown anymore, as it then filters by `tl_user.language = ''`.

So the example in the README should be updated to something else :). May be `tl_news` or something.

**Comment by qzminski** [comment]
Thanks, I changed this in 644ceb3.
