### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by Toflar** [terminal42/contao-DC_Multilingual#56]
Let's add a changelog for v4 documenting the changes and BC breaks.
I like this format: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/CHANGELOG.md#200
Wdyt?

**Comment by qzminski** [comment]
Added :+1: Feedback is welcome.

**Comment by Toflar** [comment]
The biggest bc break afaik is https://github.com/terminal42/contao-DC_Multilingual/issues/42  which is missing :)
