### ISSUE TITLE
Model::findMultipleByIds throws exception

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-DC_Multilingual#59]
If I call `findMultipleByIds` of a model extending from `Terminal42\DcMultilingualBundle\Model\Multilingual` I get an exception:

`Unknown column 'tl_vendor_product.id' in 'where clause'` because the table name is used instead of the alias:

```sql
WHERE (t1.lang_pid=0) AND (tl_vendor_product.id IN(1)) ORDER BY FIND_IN_SET(`tl_vendor_product`.`id`, '1')
```

**Comment by richardhj** [comment]
Can you please update to version 4 and see if this fixes your problem? v4 does not use `t1` anymore as alias, but the full table name.

see https://github.com/terminal42/contao-DC_Multilingual/blob/944371f81b701160191abac10ea496cb71ca9b2c/src/QueryBuilder/MultilingualQueryBuilder.php#L105 vs. https://github.com/terminal42/contao-DC_Multilingual/blob/8fef15ab3a14078f72beb78e7e10a5416d6eaa7e/src/QueryBuilder/MultilingualQueryBuilder.php#L120

**Comment by dmolineus** [comment]
Oh, I missed that meanwhile a new major release exists. Version 4 fixes the issue.
