### ISSUE TITLE
Copying tl_news with tl_content results in double translations for the copied tl_content record

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-DC_Multilingual#67]
Hello,

I think this is related to https://github.com/terminal42/contao-DC_Multilingual/issues/14.

Steps to reproduce:

1. Create a tl_news (DC_Multilingual)
2. Create a language record for the news
3. Create a tl_content (DC_Multilingual) which is a child of the news created before
4. Create a language record for the content element
5. Copy the news

Result:

The `langPid` column is not updated and is still pointing to the *copied, original* `tl_news` record which is causing the translation to appear doubled in the frontend.

It seems to be the following line:

https://github.com/terminal42/contao-DC_Multilingual/blob/master/src/Driver.php#L682

Thanks in advance for digging into it!

Bye Defcon0

**Comment by Defcon0** [comment]
In fact, we switched to core means (multiple archives for multiple languages) and a new bundle of ours for entities without parent (tl_member vs. tl_news for example): https://github.com/heimrichhannot/contao-multilingual-fields-bundle

Hence, I personally won't finish the PR to be honest. Can't speak for the rest of heimrichhannot though. If desired, I can close this issue and the PR.

**Comment by aschempp** [comment]
I don't think changing the core `tl_news` and `tl_content` tables to `DC_Multilingual` is a supported use case, I'm therefore closing this issue.
