### ISSUE TITLE
Internal Server Error | AbstractTablePickerProvider

### ISSUE THREAD

**Issue by electricarts** [terminal42/contao-DC_Multilingual#82]
When I try to edit the pages in the backend of a 4.4 Contao installation after moving to a new server, I get the following error message: 

`[2023-02-04 12:42:51] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AbstractTablePickerProvider\" from namespace \"Contao\\CoreBundle\\Picker\".\nDid you forget a \"use\" statement for another namespace? at /home/mario/webapps/contao/vendor/terminal42/dc_multilingual/src/Picker/MultilingualPickerProvider.php:27)"} []`

What can/should i do?

**Comment by rabauss** [comment]
Contao 4.4 is EOL - you should at least upgrade to 4.9
And the dependencies should get updated in this extension because the `AbstractTablePickerProvider` is not available in 4.4!

**Comment by aschempp** [comment]
closing this since we don't support Contao 4.4 anymore.
